name = "Rubik"
defaultTargets = ["rubik"]

[leanOptions]
pp.unicode.fun = true
pp.proofs.withType = false
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.15.0"

[[lean_lib]]
name = "rubik"
globs = ["Rubik.*"]
